### ISSUE TITLE
Memory leak with "laplace" still present?

### ISSUE THREAD

**Issue by harrysouthworth** [gbm-developers/gbm3#16] opened 2015-03-16 19:54 UTC
_From @johnrolfeellis on March 11, 2014 4:2_

I'm experiencing a significant memory leak in 2.1-0.3 with the "laplace" distribution, similar to what is described here:

https://code.google.com/p/gradientboostedmodels/issues/detail?id=32

The file laplace.cpp was fixed at line 97 in 2.1-0.3 to address this.  But though I'm running 2.1-0.3 (at least that's what "library (gbm)" says), I'm stilling getting a memory leak.

The training set has 280K rows with 11 columns, and the parameters are:    

```
gbm.fit (trainingSet, outcomes, nTrain = 279870, distribution = "laplace", interaction.depth = 4, n.trees = 1000)
```

which uses 1.1 GB of working set and 4.7 GB of committed memory.   And very roughly, adding 2000 more trees uses an additional 2 GB of working set and 4-5 GB of committed memory.   But when the distribution is changed "gaussian", the working set and committed memory stay around 550M, no matter how many trees.

I tried building the master branch, but gbm.fit() doesn't appear to work:

```
Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1           nan             nan     0.0010       nan
     2           nan             nan     0.0010       nan
     3           nan             nan     0.0010       nan
```

(R version 3.0.2, gbm 2.1-0.3, Windows 7 64-bit.)

_Copied from original issue: harrysouthworth/gbm#11_

**Comment by harrysouthworth** [comment] 2015-03-16 19:54
_From @johnrolfeellis on March 11, 2014 18:16_

Also, I can package up the training set and make it available privately if that would help.

**Comment by harrysouthworth** [comment] 2015-08-18 08:36
Using build from pdfmetcalfe/gbm on branch 'no-multinomial'.

I've just been using distribution="laplace" with a dataset with ~1000 observations and ~200 variables and see no evidence of memory leakage. Are others still getting this problem?

Harry

**Comment by pdmetcalfe** [comment] 2015-10-16 17:38
Closing this due to lack of evidence.

**Closed as completed by pdmetcalfe** 2015-10-16 17:38 UTC

**Comment by apiskors** [comment] 2016-07-15 06:23
In my tests, gbm 2.1.1 still has a HUGE memory leak with "laplace", while the old gbm_1.6-3.2.tar.gz from 2012 (available on CRAN) works just fine.  I do not yet have an isolated test case I can provide, but AFAICT all 2.x versions of gbm have the problem, while 1.x do not.  The GitHub master branch does not currently compile, so I couldn't test that.

Good, no memory leak:
https://cran.r-project.org/src/contrib/Archive/gbm/gbm_1.6-3.2.tar.gz

**Comment by pdmetcalfe** [comment] 2016-07-15 07:56
Can you give more information on "does not compile"?  It builds on Travis and is currently passing its tests there, so we would need more information to understand that.

**Comment by apiskors** [comment] 2016-07-15 10:14
Does the GitHub head gbm require some specific version of Rcpp or R itself?  I am still using Rcpp 0.11.1 dated 2014-03-12, and R 3.1.0 (Patched), 2014-04-25, svn.rev 65494.  This is what I get when I try to compile the gbm head:

```
* installing *source* package 'gbm' ...
** libs
*** arch - x86_64
g++ -I/usr/local/pkg/R-3.1-branch-20140425/lib/R/include -I/usr/local/pkg/R-3.1-branch-20140425/lib/R/include/x86_64 -DNDEBUG  -I/usr/local/include -I"/home/local-x86_64-ubuntu/pkg/R-3.1-branch-20140425/lib/R/site-library/Rcpp/include"   -fpic  -g -O2  -c bernoulli.cpp -o bernoulli.o
bernoulli.cpp: In member function 'virtual void CBernoulli::FitBestConstant(const CDataset&, const Bag&, const double*, long unsigned int, std::vector<double>&, CCARTTree&)':
bernoulli.cpp:131:13: error: 'warning' is not a member of 'Rcpp'
make: *** [bernoulli.o] Error 1
ERROR: compilation failed for package 'gbm'
```

**Comment by pdmetcalfe** [comment] 2016-07-15 10:37
Hmm.  Looks like it needs Rcpp >= 0.11.5

http://www.r-bloggers.com/rcpp-0-11-5/

**Comment by apiskors** [comment] 2016-07-15 17:33
Ok, I installed R 3.2.5 (Patched), 2016-05-05, svn.rev 70916 and Rcpp 0.12.5 (2016-05-14).  With those and gbm 2.1.1 (2015-03-11, the latest on CRAN), I still see massive memory leaks.  After one call to gbm.fit() my R process is 727 MB, and then each time I call gbm.fit() again it leaks about 53 MB, reaching 2.8 GB after only 40 iterations.

However, I then installed the gbm GitHub head, and it appears to fix the problem, the leaks are gone!  My R hits about 350 MB in the first few iterations and then stays there, no memory growth due to calling gbm.fit().

(So I assume you don't care about my test case, since the latest code no longer shows the problem.)

**Comment by JackStat** [comment] 2016-07-15 17:37
If the test can be easily incorporated then it will help us monitor and prevent the issue in the future as the code changes. I am happy to incorporate the test formally if you have a script that you can share

**Comment by pdmetcalfe** [comment] 2016-07-15 18:17
A bunch of allocation errors went away when I converted it to RAII.

You might also find that building the head version with OpenMP support gives you useful new stuff...

**Comment by leegl** [comment] 2016-07-18 16:05
Some people find that they have a memory leak and others do not.  One possible explanation for this is the OS.  

I installed R and the gbm package on two nearly identical computers, except one ran Windows and the other ran Linux*.   Ran identical R script using repeated gbm() calls with laplace distribution selected.  No memory leak in Windows but huge memory leak under Linux that eventually leads to "unable to allocate memory" error.  

A patch fix for this in gbm v. 2.0-8 has been posted  but apparently not incorporated into later gbm versions:  http://r-forge.r-project.org/tracker/?atid=1813&group_id=443&func=browse.  Next, I will see if I can successfully apply the above patch to the R version installed on my Linux system.

*R v. 3.3.1 and gbm v. 2.2.1 installed on either Windows 8.1 or Linux Debian 8.5 using the Gnome GUI on two different computers with the same motherboard (Asus M2N68-AM Plus) and memory card manufacturer/model.

**Comment by apiskors** [comment] 2016-07-20 13:33
Attached is a zipfile containing two files to reproduce the gbm.fit() laplace memory leak, "show-memleak.R" and "gbm-fit-data-20160720.RData".  I ran it like so:

```
/usr/local/bin/R --vanilla --no-restore --no-save --silent < show-memleak.R
```

I am using this version of R (built from source):

```
andy@pinky:~/studies/gbm-memleak-201607$ /usr/local/bin/R --version | head -n 3
R version 3.2.5 Patched (2016-05-05 r70929) -- "Very, Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu/x86_64 (64-bit)
```

[gbm-memleak-20160720.zip](https://github.com/gbm-developers/gbm/files/373757/gbm-memleak-20160720.zip)

**Comment by apiskors** [comment] 2016-07-20 18:43
"leegl", thank you for pointing us to that patch:

http://r-forge.r-project.org/tracker/index.php?func=detail&aid=2678&group_id=443&atid=1813
http://r-forge.r-project.org/tracker/download.php/443/1813/2678/433/gbm_patch.diff

That patch is very simple!  It just adds two appropriate "delete" calls, one each laplace.cpp and multinomial.cpp.  The change to laplace.cpp is an improvement, but is not sufficient by itself.  However, fully fixing the leak is very easy!  All laplace.cpp needs is two add TWO "delete" calls at the end of the CLaplace::FitBestConstant function, like so:

```
delete[] adW2;  delete[] adArr;
```

Making that change to gbm 2.1.1 fully fixes the laplace memory leak shown by my test case above.  I did not test multinomial.

**Comment by apiskors** [comment] 2016-07-20 19:22
Btw, on my laplace test case above (20 iterations of 2,000 trees), the latest GitHub code is about 60% slower than the old gbm 1.6-3.2, 15 vs. 9.3 seconds.  The patched gbm 2.1.1 takes 10 seconds.

**Comment by leegl** [comment] 2016-07-21 12:16
Thank you for the info on the patch, apiskors, and for those extra two lines of code to fully fix the memory leak in laplace.cpp so that gbm() does not have a memory leak when it used the laplace (and multinomial) distribution.  

I remove gbm 2.1.1  and installed the version of gbm() currently maintained by Harry Southworth at https://github.com/gbm-developers/gbm.  It worked well on the Linux Debian Gnome system described in my early message.  As you see below, I had to install libcurl and libxml2 in the Linux shell first.  The command sequence I used was:

In Linux console:
apt-get -y build-dep libcurl4-gnutls-dev
apt-get -y install libcurl4-gnutls-dev
apt-get -y build-dep libxml2-dev
apt-get -y install libxml2-dev 

In R:
remove.packages("gbm")
install.packages("devtools", dependencies=TRUE)
library(devtools)
install_github("gbm-developers/gbm") <--  _Updated: Use gbm-developers/gbm (not harrysouthworth/gbm, which was shown here earlier). See comment below by pdmetcalfe)._

Again, this version of gbm worked without overwhelming memory leaks.  I did notice that the resulting fit objects (gbm.object)  took up about twice as much memory as the same objects when running under Windows 8.1 (as reported by the OS).  This might be due to the need for the two additional delete[] statements you mentioned above.  

--Lee

Keywords:  cannot allocate memory leak gbm.object gc() fragmentation returned to OS

**Comment by pdmetcalfe** [comment] 2016-07-22 10:34
To try to reduce confusion...

The _current_ development version of gbm is that which is at https://github.com/gbm-developers/gbm.  It has lots of interesting new features (e.g. core search algorithm parallelization using openmp, cox regression for start-stop data), and lots of fixed bugs (e.g. cox regression now works, memory leaks have gone, the C++ code is now ubsan clean, plot now works).  We will be submitting this version, probably as gbm 3.0, to CRAN in not-too-long.

The C++ is (now) written using the resource-acquisition-is-initialization (RAII) style, which makes it quite difficult to introduce memory leaks.

Old versions _have_ had memory leaks.  Various patches for fixing them have existed at various stages.  They are now - all - obsolete!

If you have a bug against the master branch of https://github.com/gbm-developers/gbm, please file a fresh issue and please don't resurrect this one!

Thanks!

**Comment by apiskors** [comment] 2016-07-22 12:09
I'm not aware of any confusion, but yes, everything pdmetcalfe said above is quite correct.  I'm surprised though how basic and easy to fix the (known) gbm 2.x memory leak bugs were.  So it may be worth issuing a 2.1.2 point release of that old 2.x branch.

**Comment by leegl** [comment] 2016-07-22 13:14
The gbm-developers/gbm version does work great without memory leaks when laplace and multinomial distributions are used.  However, its availability is not widely know, so a new release of gbm() across all of the cran mirrors would be helpful to many people.  I am going to go ahead and post the availability of gbm-developers/gbm on other sites where people are struggling with the latest versions.

**Comment by afranks86** [comment] 2017-09-21 17:42
I am running the gbm-developers/gbm version (2.1.3.9000) on MacOSX Sierra and seem to have big memory leaks using the Laplace distribution.  I discovered this because the OS killed my R process. 
 Any thoughts? When I switch to "tdist", for example, I don't have problems.

**Comment by pdmetcalfe** [comment] 2017-09-21 19:03
Do you have a minimal test case?

Thx!

**Comment by afranks86** [comment] 2017-09-21 21:24
The simple example below seems to lead to a memory leak.  The memory of the R process grows seemingly unbounded each time gbm is called.   There is an unrelated error which I believe I saw mentioned elsewhere as well: I can't use CV option without an error when I'm fitting a simple model with a single predictor.  It works if I add a dummy variable though (in this case z).  This is the simplest example that is close to my setting.

```library(gbm)
n <-  100
for(i in 1:100) {
     print(i)
     x <- 1:n
     y <- 3 * x + rexp(n) * ifelse(runif(n) < 0.5, -1, 1)
     df <- data.frame(x=x, y=y, z=rep(1, n))
     fit_cv <- gbm(y ~ x + z, data=df, distribution="laplace", n.trees=5000, cv.folds=10, verbose=FALSE)
     opt_iters <- gbm.perf(fit_cv, method="cv")
     best_fit <- predict(fit_cv, df, opt_iters)
 
 }```

**Comment by afranks86** [comment] 2017-09-21 21:43
Actually I believe was using an old version.  I had originally installed from [https://github.com/gbm-developers/gbm](url).  When installing from [https://github.com/gbm-developers/gbm](url) it seemed to fix both issues mentioned above.  However, on my machine gbm3 failed to install because of OpenMP.  I had to follow these instructions before I was successfully able to install it: [http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/](url)
