### ISSUE TITLE
More notes on coxph

### ISSUE THREAD

**Issue by therneau** [gbm-developers/gbm3#59] opened 2015-08-17 14:16 UTC
Our group is using gbm survival models more and so I am motivated to contribute a solid fix to this.  I have C code that is rock solid, it may require a bit of input from you all to convert it to C++.  Last time I counted I think there were 11 different computer languages in which I've done substantive work at some time in my career, but C++ isn't on the list.  Three issues that need to be sorted out before I dive in:
1. Stratified Cox models.  These have a lot of uses.  The loglik and derivative for each subject are computed within strata.  Do you want to allow it?   Easy for the user to specify, but one more variable to pass down the calling chain.
2. Breslow vs Efron approximation.  The survival::coxph and coxm::coxme functions use the Efron approx by default, most of the rest of the world defaults to Breslow.  The latter is a tad easier to program and ends up as the default because it was done first and Efron added later.   I use Efron because it is the more accurate one and I like to dot the i, but in most data sets the difference between the two is so small as to not be relevant.  There is one counterexample: stratified logistic regression.  This is used for matched case-control studies, common in epidemiology and now showing up a fair bit in genetic association studies.  It can be fit using a stratified Cox model, and for this you want Efron.  I don't know if you are getting requests for stratified logistic.
   You can decide to do only Efron, only Breslow, or allow it as an option.  If an option that is another argument to pass down the chain.
3. Counting process data.  This is hugely useful.  Users have  Surv(time1, time2, status) ~ x1 + x2 +... as the formula, so it makes no impact on them.  Again, more variables to pass down the calling chain.

Looking at the code, you have chosen to make all of the fitting routines have the same argument list.  One thing that I did in rpart might be an approach, which was to let y be a matrix and pass nrow/ncol.

Terry T.

**Comment by gregridgeway** [comment] 2015-08-19 16:48
The issue is less about C versus C++ but rather having the right gradient computations. Have a look at the vignette

github.com/gbm-developers/gbm/blob/master/inst/doc/gbm.pdf

If you have code for all of the necessary steps, then it is pretty easy to add a new distribution class to the package. 

Figure 2 shows the basic algorithm. The cox likelihood is more complex since it isn't a simple sum as shown in the figure, but the steps are basically the same. We need an initial value (0 is fine for Cox). We need the gradient d/df(x) Psi(t,delta,f(x)). We need the terminal node values.

I would suggest starting with the coxph.cpp source. Copy it to coxphefron.cpp. Modify it so that it does Efron approximation. You might be able to reuse much of the code you already have. See if you can get that far. If so, then I think the rest will come easy.

You can use the misc parameter in gbm.fit to pass extra parameters to the gbm engine.

Greg

**Comment by pdmetcalfe** [comment] 2015-08-21 08:38
Sorry for the delay in answering - holiday time...

Terry: should I add you to the developers mailing list, which makes conversation a bit easier?

It would be insanely great to get cox sorted out. I'd really like to get the multinomial dealt with first. Then I think we'll be in a slightly tidier place, and it will be easier to add new stuff.

Can you point me at some approximation to the code we need - from coxme?

Cheers,

pdm

**Comment by therneau** [comment] 2015-08-21 14:17
Paul,
   Yes, add me to the list if it makes conversation easier.
   I'm off to the ISCB meeting tomorrow, so won't be doing anything for the next week.

   Looking ahead, to do Cox in the most general form is not computationally more difficult 
than the current, but needs extra variables.  If you could start thinking about how we 
would best pass them down to the code -- "back burner" of your thoughts -- that would be nice.
    gbm(Surv(time, status) ~ x1 + .... + strata(zed), data=ddd)   # simple Cox
    gbm(Surv(time1, time2, status) ~ x1 + x2 + x3 + .... + strata(zed), data=whatever, 
...) # Andersen-Gill

```
For the first case my standard code has the data sorted in strata, reverse time, 
```

status order.  (Either forward or inverse time would be ok).  There is a created 0/1 
variable "newstrat" which is 1 if the observation is the first of a new strata.  Given 
that gbm likes to use subsets in many spots it might be better to use 
newstrat=match(strata, strata) which gives an integer result. Users can use numeric or 
factor or character or logical as a strata, I've seen them all.  The end of the line code 
needs time, status, newstrat, and the risk score f.  If there is not strata in the formula 
I manufacture a single stratum "newstrat".

```
For the Andersen Gill case I current don't sort the data in time order, but instead 
```

add two indices:
      indx1 = order(strata, time1, status)
      indx2 = order(strata, time2, status)
and now there are 6 variables passed down the chain instead of 4. The use of two indices 
rather than a single sort is critical: it allows the computation time to be O(2n) rather 
than O(n^2) for the Andersen Gill.

  In terms of model formulua, the " + strata(variable)" is common across the survival 
routines so from a users point of view it would be nice to maintain.  The code needs to 
notice it and remove that term before creating the X matrix, which is a minor nuisance.  
The choice of Efron/Breslow approximation for ties is a simple parameter.

Terry Therneau

**Comment by gregridgeway** [comment] 2015-08-22 14:41
I think the route that would limit the amount of changes to other parts of gbm would be to pack the new parameters (time2, zed) into adMisc. Perhaps always send from gbm.fit Y=time1 and adMisc as a three column matrix with cbind(time2,status,zed). Or always send through adMisc a six column matrix cbind(time2, status, zed, newstrat, indx1, indx2). If there’s no time2 then we just fill it with NAs. The new CCoxXXX class would just know to expect adMisc in this form.

**Comment by pdmetcalfe** [comment] 2016-06-16 19:36
Now fixed, thanks to @therneau contributing his code.

**Closed as completed by pdmetcalfe** 2016-06-16 19:36 UTC
